### ISSUE TITLE
`pipe()` method is bypassing any compression middleware

### ISSUE THREAD

**Issue by nasrinaria** [royalswe/vike-fastify-boilerplate#1]
The @fastify/compress plugin is expected to automatically compress responses based on the content-type. However, this does not seem to apply when streaming HTML responses with `httpResponse.pipe(reply.raw)`. In such cases, an extra step is required: manually calling `reply.send(httpResponse.body)` to enable compression. This behavior is observed in the React sample [here](https://github.com/effector/vike-react-template/blob/main/server/server.ts#L111).

The recommendation to use pipe only with React seems irrelevant in this context, as the extra manual step is still necessary. [See reference](https://github.com/effector/vike-react-template/blob/main/server/server.ts#L111).

Steps to Reproduce
- Use the provided React sample.
- Run the server and attempt to stream an HTML response using `httpResponse.pipe(reply.raw)`.
- Observe that compression does not occur.
- Remove `httpResponse.pipe(reply.raw)` and add the following code: 
```
const body = await httpResponse.getBody()
reply.status(httpResponse.statusCode).send(body);
```
- Check `content-encoding` and `vary` in response headers 

The `pipe()` method is bypassing any compression middleware. This is because it was writing directly to the raw response object, potentially skipping other response processing steps.

**Comment by royalswe** [comment]
Thank you so much @nasrinaria  for your help. I wasn’t aware that the compression wasn’t being applied when streaming HTML responses with httpResponse.pipe(reply.raw). I appreciate the clarification and will make necessary code changes and comments about the issue.

**Comment by royalswe** [comment]
Changed from 
`from httpResponse.pipe(reply.raw)`
 to
`reply.send(await httpResponse.getReadableNodeStream());`
